### ISSUE TITLE
图标消失是怎么回事

### ISSUE THREAD

**Issue by adyliu** [zesming/ChargingHelper#1]
我安装完以后使用几次不显示APP的图标（CharingHelperPlus），但锁屏那个预计多长时间充满电还是提醒的。

iOS 7.1.1 和 iOS 7.1.2 都有此问题。

**Comment by zesming** [comment]
iOS 7就有这样的问题，这应该是appsync或者是越狱工具的一个bug

发自我的 iPhone

**Comment by adyliu** [comment]
卸载完appsync也没有找回图标，看来是得重新安装了。

**Comment by adyliu** [comment]
卸载appsync重新安装CharingHelperPlus后图标回来了。谢谢。
